CREATE TABLE IF NOT EXISTS PROPERTIES (
    ID VARCHAR(150) PRIMARY KEY,
    APPLICATION VARCHAR(50),
    PROFILE VARCHAR(50),
    LABEL VARCHAR(50),
    PROP_KEY VARCHAR(100),
    PROP_VALUE VARCHAR(200)
);
